---
- hosts: localhost
  vars:
    personal: "{{ lookup('env', 'HOME') }}/Privatespace"
  tasks:
    - import_tasks: tasks/git-setup.yml
    - import_tasks: tasks/core-setup.yml
    - import_tasks: tasks/zsh-setup.yml
    - import_tasks: tasks/dotfiles.yml
