- name: Install System Packages
  become: true
  become_exe: sudo su -
  apt:
    name:
      - dconf-editor
      - alacritty
      - meld
  tags: [install, core]
- name: Check if HomeBrew is installed
  ansible.builtin.stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew
  register: brew
  tags: [install, core]
- name: Download & Install HomeBrew
  when: not brew.stat.exists
  block:
    - name: Download Installer Script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
        dest: /tmp/brew_install.sh
        mode: '775'
    - name: Run Installer Script
      ansible.builtin.shell: NONINTERACTIVE=1 /tmp/brew_install.sh
  tags: [install, core]
- name: Set LinuxBrew Executable Path
  ansible.builtin.set_fact:
    linuxbrew_executable: /home/linuxbrew/.linuxbrew/bin/brew
    linuxbrew_path: /home/linuxbrew/.linuxbrew/bin
  tags: [install, core, brew]
- name: Check if Starship is installed
  ansible.builtin.stat:
    path: /home/{{ lookup('env', 'USER') }}/.config/starship.toml
  register: starship
  tags: [install, core]
- name: Install
  when: not starship.stat.exists
  ansible.builtin.command: '{{ linuxbrew_executable }} install starship'
  environment:
    HOME: /home/{{ lookup('env', 'USER') }}
  tags: [install, core]
- name: Install packages with brew
  community.general.homebrew:
    name:
      - node
      - tmux
      - curl
      - lsof
      - ccache
      - moreutils
      - xclip
      - gcc
      - font-anonymice-powerline
      - stow
      - font-jetbrains-mono-nerd-font
      - cmake
      - lua
      - unzip
      - libtool
      - gettext
      - docker
      - lazydocker
      - lazygit
      - zoxide
      - kubectx
      - kubectl
      - kubecm
      - k9s
      - awscli
      - awscli-local
      - docker-credential-helper-ecr
      - yazi
      - ffmpegthumbnailer
      - unar
      - jq
      - poppler
      - fd
      - ripgrep
      - fzf
      - pipx
      - go
      - atuin
      - aws-cdk
      - tmux
      - doxygen
      - rclone
      - aws-sso-util
      - flawfinder
      - bazelisk
      - git-lfs
      - uv
      - eza
      - fonts-encodings
      - font-opendyslexic-nerd-font
      - neovim
      - gawk
      - grep
      - gnu-sed
      - coreutils
      - git
      - json5
      - luarocks
      - rust
      - deno
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - git
      - bash
      - gemini-cli
      - jannis-baum/tap/vivify
      - dos2unix
      - lynx
      - claude-code
      - gh
      - viu
      - chafa
      - wget
      - composer
      - julia
      - isort
      - trash-cli
      - docx2txt
      - antiword
      - ouch
      - cmocka
      - googletest
      - lcov
      - mikhailai/misc/usbutils
      - delta
      - oven-sh/bun/bun
      - gs
      - ollama
      - bat
  tags: install, core, brew]
- name: Installing SDK Man
  become: false
  shell: curl -s 'https://get.sdkman.io' | bash
  tags: [install, core]
- name: Adding SDK Man to bash_profile
  environment:
    HOME: /home/{{ lookup('env', 'USER') }}
  lineinfile: path=$HOME/.bash_profile line={{ item }} state=present create=yes
  with_items: [source "$HOME/.sdkman/bin/sdkman-init.sh"]
  tags: [install, core]
- name: Installing Java
  args:
    executable: /bin/bash
  shell: source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install java 21.0.11-amzn
  become: false
  tags: [install, core]
